#!/bin/bash
# If run as a post-checkout script hook, and the previous and current
# HEAD are the same or if its a file checkout, don't proceed
if [[ "$(basename "$0")" = "post-checkout" && "$1" = "$2" || "$3" = "0" ]]; then
    exit 0
fi

# Show release tags
git tag -n20 -l *.*.*
